### ISSUE TITLE
Ejercicio 9, mejor con switch

### ISSUE THREAD

**Issue by ijaureguialzo** [Egibide-PROG2015/ejercicios-ud2-elementos-de-un-programa-parte-1-AitorBM#3]
La selección de lo que hay que hacer queda mejor con un switch, en vez de con esos ifs anidados. Fíjate que hay 3 caminos posibles.

**Comment by AitorBM** [comment]
Es cierto, en concreto en este ejercicio lo hice así por cambiar, porque en el anterior lo hice con switch.
